server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springclouddemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis:
  type-aliases-package: com.xph.user.pojo