# 配置端口号
server:
  port: 8080

# 配置注册到eureka上时服务的名称
spring:
  application:
    name: consumer-service

# 配置需要注册的服务
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka

# 配置user-service服务中负载均衡器使用算法为RandomRule，默认RandomRule(轮询)
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 配置超时时长
hystrix:
  command:
    # 默认的使用的超时时长 -对所有方法生效
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    # 对某个服务配置超时时长 -对此服务下的所有方法生效
    user-service: # 服务名
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
    # 方法一：针对某个方法配置超时时长 -只对此方法生效，
    # 方法二：直接在方法上写注解配置，可以见ConsumerController.java中
    # 两种同时配置时根据配置文件的时间来执行
#    queryByid: # 方法名
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1500