#配置端口号
server:
  port: 8080

#配置注册到eureka上时服务的名称
spring:
  application:
    name: consumer-service

#配置需要注册的服务
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
